// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2J7yykupD_siWp95zFJrPt8N8Cg1MAM',
    appId: '1:867697849614:web:9aaad804a05c3093b9d35f',
    messagingSenderId: '867697849614',
    projectId: 'flutter-simple-chat-5a86a',
    authDomain: 'flutter-simple-chat-5a86a.firebaseapp.com',
    storageBucket: 'flutter-simple-chat-5a86a.firebasestorage.app',
    measurementId: 'G-Z3SJBBGPKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_BH21U_3gKhJ4lOcRevIrgtTztGYh7I',
    appId: '1:867697849614:android:5ff552c90c22a71db9d35f',
    messagingSenderId: '867697849614',
    projectId: 'flutter-simple-chat-5a86a',
    storageBucket: 'flutter-simple-chat-5a86a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pJZsKsSEdxNuANfvwxUNGydEwFwpDRI',
    appId: '1:867697849614:ios:5e0ca40c48832b71b9d35f',
    messagingSenderId: '867697849614',
    projectId: 'flutter-simple-chat-5a86a',
    storageBucket: 'flutter-simple-chat-5a86a.firebasestorage.app',
    iosBundleId: 'com.example.flutterSimpleChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0pJZsKsSEdxNuANfvwxUNGydEwFwpDRI',
    appId: '1:867697849614:ios:5e0ca40c48832b71b9d35f',
    messagingSenderId: '867697849614',
    projectId: 'flutter-simple-chat-5a86a',
    storageBucket: 'flutter-simple-chat-5a86a.firebasestorage.app',
    iosBundleId: 'com.example.flutterSimpleChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS2J7yykupD_siWp95zFJrPt8N8Cg1MAM',
    appId: '1:867697849614:web:c830da7459c4b6b4b9d35f',
    messagingSenderId: '867697849614',
    projectId: 'flutter-simple-chat-5a86a',
    authDomain: 'flutter-simple-chat-5a86a.firebaseapp.com',
    storageBucket: 'flutter-simple-chat-5a86a.firebasestorage.app',
    measurementId: 'G-NPWH2VJMZG',
  );

}